repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.tmpl$'
      - id: end-of-file-fixer
        exclude: '\.tmpl$'
      - id: check-yaml
        args: ['--allow-multiple-documents']
      - id: check-json
        exclude: '\.tmpl$'
      - id: check-merge-conflict

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        args: ['-x']
        types: [shell]
        exclude: '\.tmpl$'

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.10.0-1
    hooks:
      - id: shfmt
        args: ['-i', '2', '-ci']
        exclude: '\.tmpl$'

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ['-c', '.yamllint.yml']

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.22.1
    hooks:
      - id: gitleaks
